### PR TITLE
Fix ki

### PR DESCRIPTION
**Pull request by mcreixell**

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
What is this supposed to be? I can't review without more information.

**Comment by mcreixell** [comment]
I'm trying to clean up the AXLomics repository before adding new RNAseq analyses. This only adds progress of different analyses in notebooks, not scripts. The only code changes I'm making here are to fix a bug coming from mixing KI vs KD labels. I want to merge this so I can start cleaning up from the latest version.

**Comment by mcreixell** [comment]
Can I be assigned as an admin of this repo so that I bug you only when I'd like you to review something?

**Comment by aarmey** [comment]
Done! You are now admin.

**Pull request merged**
