### PR TITLE
Various Updates

### PR DESCRIPTION
**Pull request by mcreixell**
There's a bunch of work in progress items here included in notebooks.
- General cleanup
- Time Series analysis
- Statistical analysis of AXL phenotypes
- AXL/YAP hydrogels

### CODE REVIEW

**Comment by mcreixell** [comment]
In addition to a substantial clean up, there are many items "in progress" included here that I'd like to keep working on in separate branches so I'd like to merge this for now.

**Review by aarmey — APPROVED** [review]
Ok, there's no way I can review this, but I trust you've gone through these carefully.

**Comment by mcreixell** [comment]
I'm not authorized to merge. Could you give me permission? I guess the same will happen in the DDMC repository.

**Comment by aarmey** [comment]
How about now?

**Pull request merged**
